### ISSUE TITLE
Please help fix error 

### ISSUE THREAD

**Issue by Raito00** [softScheck/tplink-smartplug#18]
I have Python 2.7 64bit
windows 10 64bit

Whe i type:
tplink-smartplug.py –t "192.168.100.115" –c "on"

I get:
C:\test>tplink-smartplug.py -t "192.168.100.115" -c "on"
Traceback (most recent call last):
  File "C:\test\tplink-smartplug.py", line 76, in <module>
    args = parser.parse_args()
  File "C:\Python27\lib\argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Python27\lib\argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Python27\lib\argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Python27\lib\argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "C:\Python27\lib\argparse.py", line 1791, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Python27\lib\argparse.py", line 2231, in _get_values
    value = self._get_value(action, arg_string)
  File "C:\Python27\lib\argparse.py", line 2260, in _get_value
    result = type_func(arg_string)
  File "C:\test\tplink-smartplug.py", line 30, in validIP
    socket.inet_pton(socket.AF_INET, ip)
AttributeError: 'module' object has no attribute 'inet_pton'

**Comment by Raito00** [comment]
I found ! :)

Just need add line: import win-inet-pton
 in tplink-smartplug.py
